import json
import time

from groq import Groq

import config

_MODEL = "llama-3.3-70b-versatile"

_SYSTEM_PROMPT = (
    "You are an expert forensic linguist specializing in AI-generated text detection.\n"
    "Your task is to analyze a piece of writing and estimate the probability that it\n"
    "was generated by a large language model (LLM) rather than written by a human.\n"
    "\n"
    "Analyze the following dimensions:\n"
    "- RHETORICAL STRUCTURE: Does the text follow a predictable AI pattern\n"
    "  (claim -> evidence -> summary)? Does every idea feel resolved with no loose\n"
    "  threads, tangents, or raw emotion?\n"
    "- VOCABULARY: Is the vocabulary competent but lacking personal idiosyncrasy?\n"
    '  Does it over-use words like "delve", "robust", "nuanced", "leverage",\n'
    '  "comprehensive", "crucial", "seamless"?\n'
    "- REGISTER CONSISTENCY: Is the tone perfectly uniform throughout, or does it\n"
    "  have the natural shifts and seams of human writing (fatigue, escalation,\n"
    "  digression)?\n"
    "- HEDGING LANGUAGE: Does hedging appear in AI-characteristic ways --\n"
    "  over-qualified statements, systematic caveats applied uniformly?\n"
    "- SIGNPOSTING: Are transitional phrases (Moreover, Furthermore, In conclusion,\n"
    "  It is worth noting) used at a density typical of LLM output?\n"
    "\n"
    "You MUST respond ONLY with a valid JSON object. Do not include any text,\n"
    "explanation, or markdown outside the JSON object.\n"
    "\n"
    "Output schema:\n"
    "{\n"
    '  "ai_probability": <float between 0.0 and 1.0>,\n'
    '  "reasoning": "<1-2 sentences identifying the most decisive signals>",\n'
    '  "key_signals": ["<signal 1>", "<signal 2>", "<signal 3>"]\n'
    "}\n"
    "\n"
    "Field definitions:\n"
    "- ai_probability: 0.0 = certainly human-written, 1.0 = certainly AI-generated.\n"
    "  Use the full range -- do not cluster near 0.5 unless genuinely uncertain.\n"
    "- reasoning: the 1-2 most decisive features that drove your score, written for\n"
    "  a technical reviewer. Name specific observations, not generic categories.\n"
    "- key_signals: exactly 2-3 specific observed textual features.\n"
    '  Examples: "high AI vocabulary marker density", "uniform sentence rhythm",\n'
    '  "absence of personal voice or idiosyncrasy", "overuse of transitional openers"\n'
    "\n"
    "---\n"
    "\n"
    'EXAMPLE 1 -- Clearly AI-generated:\n'
    "\n"
    'User: "Delving into the realm of machine learning, it is worth noting that\n'
    "neural networks have revolutionized many industries. Moreover, the robust\n"
    "framework provides a comprehensive solution to previously intractable problems.\n"
    'In conclusion, leveraging these technologies is crucial for modern enterprises."\n'
    "\n"
    "Assistant: {\n"
    '  "ai_probability": 0.95,\n'
    '  "reasoning": "Multiple high-frequency AI vocabulary markers (\'delve\', \'robust\', \'comprehensive\', \'leverage\', \'crucial\') appear in only 4 sentences, and the text follows the exact claim-to-evidence-to-summary rhetorical pattern typical of LLM output.",\n'
    '  "key_signals": ["high AI vocabulary marker density", "heavy transitional opener usage (Moreover, In conclusion)", "perfectly resolved rhetorical structure with no loose threads"]\n'
    "}\n"
    "\n"
    "EXAMPLE 2 -- Clearly human-written:\n"
    "\n"
    'User: "been thinking about the ML stuff we talked about last week. honestly still not sure neural nets are the right call for our use case -- we\'ve got like maybe 200 labeled examples total? tried a basic logistic regression first (took 20 mins, worked ok) but my manager keeps pushing for \'something fancier\'. idk. will probably just run both and see what blows up first"\n'
    "\n"
    "Assistant: {\n"
    '  "ai_probability": 0.04,\n'
    '  "reasoning": "Strongly human-authored: stream-of-consciousness structure with unresolved thoughts, informal register with contractions and hedging (\'honestly\', \'idk\'), specific situational detail (200 examples, 20 minutes), and no AI-characteristic signposting or vocabulary.",\n'
    '  "key_signals": ["informal register with natural hedging and uncertainty", "absence of transitional signposting", "unresolved ideas and raw pragmatic concern (manager pressure)"]\n'
    "}"
)


def _sleep_if_retrying(attempt: int) -> None:
    if attempt < config.LLM_MAX_RETRIES:
        delay = config.LLM_RETRY_BASE_DELAY * (2 ** (attempt - 1))
        time.sleep(delay)


def compute_llm_score(text: str) -> float | None:
    """Call Groq LLM to estimate AI-authorship probability.

    Returns a float in [0, 1] on success, or None if all retries fail.
    """
    client = Groq()

    for attempt in range(1, config.LLM_MAX_RETRIES + 1):
        print(f"[INFO] LLM call attempt {attempt}/{config.LLM_MAX_RETRIES}")
        try:
            response = client.chat.completions.create(
                model=_MODEL,
                messages=[
                    {"role": "system", "content": _SYSTEM_PROMPT},
                    {"role": "user", "content": text},
                ],
                temperature=0.0,
                max_tokens=300,
            )
            raw = response.choices[0].message.content.strip()

            try:
                data = json.loads(raw)
            except json.JSONDecodeError:
                print(
                    f"[WARN] LLM attempt {attempt}: response is not valid JSON;"
                    f" content={raw[:120]!r}"
                )
                _sleep_if_retrying(attempt)
                continue

            if "ai_probability" not in data:
                print(f"[WARN] LLM attempt {attempt}: response JSON missing 'ai_probability' key")
                _sleep_if_retrying(attempt)
                continue

            try:
                val = float(data["ai_probability"])
            except (TypeError, ValueError):
                print(
                    f"[WARN] LLM attempt {attempt}: ai_probability={data['ai_probability']!r}"
                    " is not numeric"
                )
                _sleep_if_retrying(attempt)
                continue

            if not (0.0 <= val <= 1.0):
                print(
                    f"[WARN] LLM attempt {attempt}: ai_probability={val} out of [0,1];"
                    " clamping"
                )
                val = max(0.0, min(1.0, val))

            print(f"[INFO] LLM signal: ai_probability={val:.4f}")
            return round(val, 4)

        except Exception as exc:
            print(f"[WARN] LLM attempt {attempt} failed: {type(exc).__name__}: {exc}")
            _sleep_if_retrying(attempt)

    print(f"[ERROR] LLM all {config.LLM_MAX_RETRIES} attempts failed — falling back to heuristics-only")
    return None
